In [26]:
import pandas as pd
import numpy as np
import os
import csv

In [27]:
# Read the CSV file
csv_path = "../Source/CrimeData/crimedata2016to2018.csv"
crmcls_df = pd.read_csv(csv_path)

crmcls_df = crmcls_df[np.isfinite(crmcls_df['Zip Codes'])]

In [28]:
# Remove NaN rows
crmcls_df.dropna(axis=1,how='any')

# Drop Columns
crmcls_df.drop(columns=['Date Reported','Reporting District','Cross Street','Location ','MO Codes',
                        'Status Code','Status Description','Crime Code 1','Crime Code 2','Crime Code 3',
                        'Crime Code 4'],inplace=True)

In [29]:
# Change Data Type
crmcls_df['Zip Codes'] = crmcls_df['Zip Codes'].astype(int)
crmcls_df['Date Occurred'] = pd.to_datetime(crmcls_df['Date Occurred'])

In [30]:
# Converting from date to year
crmcls_df['Date Occurred'] = crmcls_df['Date Occurred'].apply(lambda yr:yr.year)

In [31]:
# Filter data down to 2016 - 2018
crmcls_df = crmcls_df[crmcls_df["Date Occurred"] > 2015]

In [32]:
# Grouping data by Zip Code and Date Occurred Year
crmcls_df.groupby(['Zip Codes','Date Occurred']).count()

                         DR Number  Time Occurred  Area ID  Area Name  \
Zip Codes Date Occurred
90001     2016                 841            841      841        841
          2017                 872            872      872        872
90002     2016                2767           2767     2767       2767
          2017                2716           2716     2716       2716
90003     2016                6503           6503     6503       6503
          2017                6442           6442     6442       6442
          2018                   1              1        1          1
90004     2016                2530           2530     2530       2530
          2017                3521           3521     3521       3521
          2018                 673            673      673        673
90005     2016                1766           1766     1766       1766
          2017                1920           1920     1920       1920
          2018                   9              9        9          9
90006     2016                2452           2452     2452       2452
          2017                3226           3226     3226       3226
          2018                 614            614      614        614
90007     2016                 923            923      923        923
          2017                3214           3214     3214       3214
          2018                2254           2254     2254       2254
90008     2016                  58             58       58         58
          2017                2986           2986     2986       2986
          2018                2603           2603     2603       2603
90010     2016                 908            908      908        908
          2017                 982            982      982        982
90011     2016                5510           5510     5510       5510
          2017                5470           5470     5470       5470
          2018                   1              1        1          1
90012     2016                 241            241      241        241
          2017                2812           2812     2812       2812
          2018                3079           3079     3079       3079
...                            ...            ...      ...        ...
91406     2017                2765           2765     2765       2765
          2018                   1              1        1          1
91411     2016                 506            506      506        506
          2017                1710           1710     1710       1710
91423     2016                 576            576      576        576
          2017                1918           1918     1918       1918
91436     2016                 699            699      699        699
          2017                 740            740      740        740
91504     2016                  52             52       52         52
          2017                  70             70       70         70
91505     2016                  82             82       82         82
          2017                 117            117      117        117
91506     2016                   1              1        1          1
          2017                   2              2        2          2
91601     2016                2584           2584     2584       2584
          2017                2817           2817     2817       2817
91602     2016                 930            930      930        930
          2017                 895            895      895        895
91604     2016                1701           1701     1701       1701
          2017                1827           1827     1827       1827
          2018                   1              1        1          1
91605     2016                3179           3179     3179       3179
          2017                3237           3237     3237       3237
91606     2016                2350           2350     2350       2350
          2017                2525           2525     2525       2525
91607     2016                1369           1369     1369       1369
          2017                1356           1356     1356       1356
91801     2017                  12             12       12         12
          2018                   6              6        6          6
91803     2018                   1              1        1          1

                         Crime Code  Crime Code Description  Victim Age  \
Zip Codes Date Occurred
90001     2016                  841                     841         841
          2017                  872                     872         872
90002     2016                 2767                    2767        2767
          2017                 2716                    2716        2716
90003     2016                 6503                    6503        6503
          2017                 6442                    6442        6442
          2018                    1                       1           1
90004     2016                 2530                    2530        2530
          2017                 3521                    3521        3521
          2018                  673                     673         673
90005     2016                 1766                    1766        1766
          2017                 1920                    1920        1920
          2018                    9                       9           9
90006     2016                 2452                    2452        2452
          2017                 3226                    3226        3226
          2018                  614                     614         614
90007     2016                  923                     923         923
          2017                 3214                    3214        3214
          2018                 2254                    2254        2254
90008     2016                   58                      58          58
          2017                 2986                    2986        2986
          2018                 2603                    2603        2603
90010     2016                  908                     908         908
          2017                  982                     982         982
90011     2016                 5510                    5510        5510
          2017                 5470                    5470        5470
          2018                    1                       1           1
90012     2016                  241                     241         241
          2017                 2812                    2812        2812
          2018                 3079                    3079        3079
...                             ...                     ...         ...
91406     2017                 2765                    2765        2765
          2018                    1                       1           1
91411     2016                  506                     506         506
          2017                 1710                    1710        1710
91423     2016                  576                     576         576
          2017                 1918                    1918        1918
91436     2016                  699                     699         699
          2017                  740                     740         740
91504     2016                   52                      52          52
          2017                   70                      70          70
91505     2016                   82                      82          82
          2017                  117                     117         117
91506     2016                    1                       1           1
          2017                    2                       2           2
91601     2016                 2584                    2584        2584
          2017                 2817                    2817        2817
91602     2016                  930                     930         930
          2017                  895                     895         895
91604     2016                 1701                    1701        1701
          2017                 1827                    1827        1827
          2018                    1                       1           1
91605     2016                 3179                    3179        3179
          2017                 3237                    3237        3237
91606     2016                 2350                    2350        2350
          2017                 2525                    2525        2525
91607     2016                 1369                    1369        1369
          2017                 1356                    1356        1356
91801     2017                   12                      12          12
          2018                    6                       6           6
91803     2018                    1                       1           1

                         Victim Sex  Victim Descent  Premise Code  \
Zip Codes Date Occurred
90001     2016                  698             698           841
          2017                  737             737           872
90002     2016                 2442            2442          2767
          2017                 2344            2344          2716
90003     2016                 5564            5564          6503
          2017                 5514            5514          6442
          2018                    1               1             1
90004     2016                 2289            2289          2530
          2017                 3179            3179          3521
          2018                  603             603           673
90005     2016                 1608            1608          1766
          2017                 1761            1761          1920
          2018                    8               8             9
90006     2016                 2223            2223          2452
          2017                 2850            2850          3226
          2018                  540             540           614
90007     2016                  785             785           923
          2017                 2914            2913          3214
          2018                 2103            2103          2254
90008     2016                   57              57            58
          2017                 2771            2771          2986
          2018                 2442            2442          2603
90010     2016                  846             846           908
          2017                  907             907           982
90011     2016                 4691            4691          5510
          2017                 4622            4622          5470
          2018                    1               1             1
90012     2016                  228             228           241
          2017                 2649            2649          2812
          2018                 2911            2911          3079
...                             ...             ...           ...
91406     2017                 2479            2479          2765
          2018                    1               1             1
91411     2016                  461             461           506
          2017                 1585            1584          1710
91423     2016                  542             542           576
          2017                 1802            1802          1917
91436     2016                  668             668           699
          2017                  701             701           740
91504     2016                   42              42            52
          2017                   56              56            70
91505     2016                   77              77            82
          2017                  108             108           117
91506     2016                    0               0             1
          2017                    2               2             2
91601     2016                 2326            2326          2584
          2017                 2579            2579          2817
91602     2016                  834             834           930
          2017                  831             831           895
91604     2016                 1594            1594          1701
          2017                 1718            1718          1827
          2018                    1               1             1
91605     2016                 2813            2813          3179
          2017                 2852            2852          3237
91606     2016                 2098            2098          2350
          2017                 2242            2242          2525
91607     2016                 1264            1264          1369
          2017                 1241            1241          1356
91801     2017                    9               9            12
          2018                    6               6             6
91803     2018                    1               1             1

                         Premise Description  Weapon Used Code  \
Zip Codes Date Occurred
90001     2016                           841               387
          2017                           872               430
90002     2016                          2767              1514
          2017                          2716              1412
90003     2016                          6503              3338
          2017                          6442              3410
          2018                             1                 1
90004     2016                          2530               815
          2017                          3521              1182
          2018                           673               270
90005     2016                          1766               657
          2017                          1920               777
          2018                             9                 4
90006     2016                          2452              1011
          2017                          3226              1304
          2018                           614               306
90007     2016                           923               307
          2017                          3214              1053
          2018                          2254               780
90008     2016                            58                13
          2017                          2986              1174
          2018                          2603              1048
90010     2016                           908               321
          2017                           982               366
90011     2016                          5510              2563
          2017                          5470              2471
          2018                             1                 1
90012     2016                           241                84
          2017                          2812               959
          2018                          3079              1112
...                                      ...               ...
91406     2017                          2765               758
          2018                             1                 1
91411     2016                           506               117
          2017                          1710               434
91423     2016                           576                96
          2017                          1917               288
91436     2016                           699               120
          2017                           740               127
91504     2016                            52                 9
          2017                            70                18
91505     2016                            82                15
          2017                           117                18
91506     2016                             1                 0
          2017                             2                 0
91601     2016                          2584               666
          2017                          2817               783
91602     2016                           930               157
          2017                           895               161
91604     2016                          1701               279
          2017                          1827               330
          2018                             1                 1
91605     2016                          3179               926
          2017                          3237               906
91606     2016                          2350               538
          2017                          2525               685
91607     2016                          1369               249
          2017                          1356               293
91801     2017                            12                 2
          2018                             6                 2
91803     2018                             1                 1

                         Weapon Description  Address
Zip Codes Date Occurred
90001     2016                          387      841
          2017                          430      872
90002     2016                         1514     2767
          2017                         1412     2716
90003     2016                         3338     6503
          2017                         3410     6442
          2018                            1        1
90004     2016                          815     2530
          2017                         1182     3521
          2018                          270      673
90005     2016                          657     1766
          2017                          777     1920
          2018                            4        9
90006     2016                         1011     2452
          2017                         1304     3226
          2018                          306      614
90007     2016                          307      923
          2017                         1053     3214
          2018                          780     2254
90008     2016                           13       58
          2017                         1174     2986
          2018                         1048     2603
90010     2016                          321      908
          2017                          366      982
90011     2016                         2563     5510
          2017                         2471     5470
          2018                            1        1
90012     2016                           84      241
          2017                          959     2812
          2018                         1112     3079
...                                     ...      ...
91406     2017                          758     2765
          2018                            1        1
91411     2016                          117      506
          2017                          434     1710
91423     2016                           96      576
          2017                          288     1918
91436     2016                          120      699
          2017                          127      740
91504     2016                            9       52
          2017                           18       70
91505     2016                           15       82
          2017                           18      117
91506     2016                            0        1
          2017                            0        2
91601     2016                          666     2584
          2017                          783     2817
91602     2016                          157      930
          2017                          161      895
91604     2016                          279     1701
          2017                          330     1827
          2018                            1        1
91605     2016                          926     3179
          2017                          906     3237
91606     2016                          538     2350
          2017                          685     2525