In [48]:
import pandas as pd
import numpy as np
import os
import csv

In [49]:
# Read the CSV file
csv_path = "../Source/ForeclosureData/Registered_Foreclosure_Properties_2016-2018_Combined.csv"
forcls_df = pd.read_csv(csv_path)

forcls_df = forcls_df[np.isfinite(forcls_df['PropertyZip'])]

In [50]:
# Remove NaN rows
forcls_df.dropna(axis=1,how='any')

# Drop Columns
forcls_df.drop(columns=['Lender'],inplace=True)

In [51]:
# Chagne Data Type
forcls_df['PropertyZip'] = forcls_df['PropertyZip'].astype(int)
forcls_df['RegisteredDate'] = forcls_df['RegisteredDate'].astype('datetime64')

In [52]:
# Converting from date to year
forcls_df['RegisteredDate']=forcls_df['RegisteredDate'].apply(lambda yr:yr.year)

In [53]:
# Grouping data by PropertyZip, RegisteredDate and CouncilDistrict
forcls_df.groupby(['CouncilDistrict','PropertyZip','RegisteredDate']).count()

                                            APN  PropertyType  \
CouncilDistrict PropertyZip RegisteredDate
0               0           2017              1             1
                90063       2017              1             1
                            2018              1             1
                90302       2016              1             1
                91302       2016              1             1
                            2017              1             1
                91307       2017              1             1
1               90006       2016             25            25
                            2017             14            14
                            2018             11            11
                90007       2016              3             3
                            2017              2             2
                            2018              3             3
                90012       2016              5             5
                            2017              5             5
                            2018              2             2
                90015       2016              2             2
                            2017              2             2
                            2018              2             2
                90017       2016              9             9
                            2017              4             4
                            2018              2             2
                90026       2016              6             6
                            2017              5             5
                            2018              2             2
                90031       2016             45            45
                            2017             38            38
                            2018             20            20
                90041       2016              2             2
                            2017              2             2
...                                         ...           ...
15              90059       2018             25            25
                90061       2016             19            19
                            2017             17            17
                            2018             12            12
                90247       2016             22            22
                            2017             17            17
                            2018             10            10
                90248       2016              6             6
                            2017              3             3
                            2018              6             6
                90501       2016             24            24
                            2017             21            21
                            2018             10            10
                90710       2016             45            45
                            2017             29            29
                            2018             11            11
                90717       2016              1             1
                            2017              1             1
                            2018              2             2
                90731       2016             89            89
                            2017             63            63
                            2018             41            41
                90732       2016             52            52
                            2017             29            29
                            2018             21            21
                90744       2016             95            95
                            2017             77            77
                            2018             36            36
                99999       2016              1             1
                            2017              1             1

                                            PropertyAddress  PropertyCity  \
CouncilDistrict PropertyZip RegisteredDate
0               0           2017                          1             0
                90063       2017                          1             1
                            2018                          1             1
                90302       2016                          1             1
                91302       2016                          1             1
                            2017                          1             1
                91307       2017                          1             1
1               90006       2016                         25            25
                            2017                         14            14
                            2018                         11            11
                90007       2016                          3             3
                            2017                          2             2
                            2018                          3             3
                90012       2016                          5             5
                            2017                          5             5
                            2018                          2             2
                90015       2016                          2             2
                            2017                          2             2
                            2018                          2             2
                90017       2016                          9             9
                            2017                          4             4
                            2018                          2             2
                90026       2016                          6             6
                            2017                          5             5
                            2018                          2             2
                90031       2016                         45            45
                            2017                         38            38
                            2018                         20            20
                90041       2016                          2             2
                            2017                          2             2
...                                                     ...           ...
15              90059       2018                         25            25
                90061       2016                         19            19
                            2017                         17            17
                            2018                         12            12
                90247       2016                         22            22
                            2017                         17            17
                            2018                         10            10
                90248       2016                          6             6
                            2017                          3             3
                            2018                          6             6
                90501       2016                         24            24
                            2017                         21            21
                            2018                         10            10
                90710       2016                         45            45
                            2017                         29            29
                            2018                         11            11
                90717       2016                          1             1
                            2017                          1             1
                            2018                          2             2
                90731       2016                         89            89
                            2017                         63            63
                            2018                         41            41
                90732       2016                         52            52
                            2017                         29            29
                            2018                         21            21
                90744       2016                         95            95
                            2017                         77            77
                            2018                         36            36
                99999       2016                          1             1
                            2017                          1             1

                                            PropertyState
CouncilDistrict PropertyZip RegisteredDate
0               0           2017                        1
                90063       2017                        1
                            2018                        1
                90302       2016                        1
                91302       2016                        1
                            2017                        1
                91307       2017                        1
1               90006       2016                       25
                            2017                       14
                            2018                       11
                90007       2016                        3
                            2017                        2
                            2018                        3
                90012       2016                        5
                            2017                        5
                            2018                        2
                90015       2016                        2
                            2017                        2
                            2018                        2
                90017       2016                        9
                            2017                        4
                            2018                        2
                90026       2016                        6
                            2017                        5
                            2018                        2
                90031       2016                       45
                            2017                       38
                            2018                       20
                90041       2016                        2
                            2017                        2
...                                                   ...
15              90059       2018                       25
                90061       2016                       19
                            2017                       17
                            2018                       12
                90247       2016                       22
                            2017                       17
                            2018                       10
                90248       2016                        6
                            2017                        3
                            2018                        6
                90501       2016                       24
                            2017                       21
                            2018                       10
                90710       2016                       45
                            2017                       29
                            2018                       11
                90717       2016                        1
                            2017                        1
                            2018                        2
                90731       2016                       89
                            2017                       63
                            2018                       41
                90732       2016                       52
                            2017                       29
                            2018                       21
                90744       2016                       95
                            2017                       77
                            2018                       36
                99999       2016                        1
                            2017                        1

[588 rows x 5 columns]