In [1]:
import pandas as pd
import numpy as np

In [17]:
crimedata_df = pd.read_csv("../Crimedata Output/Crime_Data_LA_Use.csv")
crimedata_df['Area Name'].unique()

array(['Central', 'Rampart', 'Southeast', 'Southwest', 'Newton',
       'Hollenbeck', '77th Street', 'Harbor', 'Hollywood', 'Wilshire',
       'Olympic', 'West LA', 'Northeast', 'Van Nuys', 'Topanga',
       'West Valley', 'Foothill', 'N Hollywood', 'Pacific', 'Mission',
       'Devonshire'], dtype=object)

In [10]:
#grab foreclosure data from 2016
crime16=crimedata_df[crimedata_df['Date Occurred Year']==2016]

#grab total foreclosure for 2016
tot_crime16=crime16["Area Name"].count()


#grab total crime for each area in 2016
seventyseven16crime=crime16["Area Name"].value_counts()["77th Street"]
central16=crime16["Area Name"].value_counts()["Central"]
dev16=crime16["Area Name"].value_counts()["Devonshire"]
fhill16=crime16["Area Name"].value_counts()["Foothill"]
harb16=crime16["Area Name"].value_counts()["Harbor"]
hbeck16=crime16["Area Name"].value_counts()["Hollenbeck"]
hwood16=crime16["Area Name"].value_counts()["Hollywood"]
mission16=crime16["Area Name"].value_counts()["Mission"]
nhwood16=crime16["Area Name"].value_counts()["N Hollywood"]
newton16=crime16["Area Name"].value_counts()["Newton"]
northeast16=crime16["Area Name"].value_counts()["Northeast"]
pacific16=crime16["Area Name"].value_counts()["Pacific"]
rampart16=crime16["Area Name"].value_counts()["Rampart"]
seast16=crime16["Area Name"].value_counts()["Southeast"]
swest16=crime16["Area Name"].value_counts()["Southwest"]
topanga16=crime16["Area Name"].value_counts()["Topanga"]
vnuys16=crime16["Area Name"].value_counts()["Van Nuys"]
wla16=crime16["Area Name"].value_counts()["West LA"]
wvalley16=crime16["Area Name"].value_counts()["West Valley"]
wilshire16=crime16["Area Name"].value_counts()["Wilshire"]


# Percentage of crime per area
per_seventyseven16crime = seventyseven16crime/tot_crime16 *100
per_central16 = central16/tot_crime16 *100
per_dev16 = dev16/tot_crime16 *100
per_fhill16 = fhill16/tot_crime16 *100
per_harb16 = harb16/tot_crime16 *100
per_hbeck16 = hbeck16/tot_crime16 *100
per_hwood16 = hwood16/tot_crime16 *100
per_mission16 = mission16/tot_crime16 *100
per_nhwood16 = nhwood16/tot_crime16 *100
per_newton16 = newton16/tot_crime16 * 100
per_northeast16 = northeast16/tot_crime16 *100
per_pacific16 = pacific16/tot_crime16 *100
per_rampart16 = rampart16/tot_crime16 *100
per_seast16 = seast16/tot_crime16 *100
per_swest16 = swest16/tot_crime16 *100
per_topanga16 = topanga16/tot_crime16*100
per_vnuys16 = vnuys16/tot_crime16 *100
per_wla16 = wla16/tot_crime16 *100
per_wvalley16 = wvalley16/tot_crime16 *100
per_wilshire16 = wilshire16/tot_crime16 *100


rate16 = pd.DataFrame({"":['77th St', 'Central', 'Devonshire', 'Foothill', 'Harbor',
                          'Hollenbeck', 'Hollywood', 'Mission', 'North Hollywood',
                          'Newton', 'Northeast',' Pacific', 'Rampart', 'Southeast',
                          'Southwest', 'Topanga', 'Van Nuys', 'West LA', 'West Valley',
                          'Wilshire'],
                           "Percentage of Crime": [per_seventyseven16crime, per_central16, per_dev16, per_fhill16, 
                                                         per_harb16,per_hbeck16, per_hwood16, per_mission16, per_nhwood16,
                                                         per_newton16,per_northeast16,per_pacific16, per_rampart16,
                                                         per_seast16, per_swest16, per_topanga16,
                                                         per_vnuys16,
                                                         per_wla16, per_wvalley16, per_wilshire16]})

rate16["Percentage of Crime"]= rate16["Percentage of Crime"].map("{:.2f}%".format)
rate16= rate16.set_index('')
rate16

                Percentage of Crime

77th St                       7.06%
Central                       1.85%
Devonshire                    4.74%
Foothill                      3.64%
Harbor                        4.37%
Hollenbeck                    4.19%
Hollywood                     4.85%
Mission                       5.06%
North Hollywood               5.52%
Newton                        5.06%
Northeast                     4.76%
 Pacific                      5.40%
Rampart                       4.20%
Southeast                     5.27%
Southwest                     6.50%
Topanga                       5.04%
Van Nuys                      4.80%
West LA                       4.31%
West Valley                   4.42%
Wilshire                      4.15%

In [11]:
#grab foreclosure data from 2017
crime17=crimedata_df[crimedata_df['Date Occurred Year']==2017]

#grab total foreclosure for 2017
tot_crime17=crime17["Area Name"].count()


#grab total crime for each area in 2017
seventyseven17crime=crime17["Area Name"].value_counts()["77th Street"]
central17=crime17["Area Name"].value_counts()["Central"]
dev17=crime17["Area Name"].value_counts()["Devonshire"]
fhill17=crime17["Area Name"].value_counts()["Foothill"]
harb17=crime17["Area Name"].value_counts()["Harbor"]
hbeck17=crime17["Area Name"].value_counts()["Hollenbeck"]
hwood17=crime17["Area Name"].value_counts()["Hollywood"]
mission17=crime17["Area Name"].value_counts()["Mission"]
nhwood17=crime17["Area Name"].value_counts()["N Hollywood"]
newton17=crime17["Area Name"].value_counts()["Newton"]
northeast17=crime17["Area Name"].value_counts()["Northeast"]
pacific17=crime17["Area Name"].value_counts()["Pacific"]
rampart17=crime17["Area Name"].value_counts()["Rampart"]
seast17=crime17["Area Name"].value_counts()["Southeast"]
swest17=crime17["Area Name"].value_counts()["Southwest"]
topanga17=crime17["Area Name"].value_counts()["Topanga"]
vnuys17=crime17["Area Name"].value_counts()["Van Nuys"]
wla17=crime17["Area Name"].value_counts()["West LA"]
wvalley17=crime17["Area Name"].value_counts()["West Valley"]
wilshire17=crime17["Area Name"].value_counts()["Wilshire"]


# Percentage of crime per area
per_seventyseven17crime = seventyseven17crime/tot_crime17 *100
per_central17 = central17/tot_crime17 *100
per_dev17 = dev17/tot_crime17 *100
per_fhill17 = fhill17/tot_crime17 *100
per_harb17 = harb17/tot_crime17 *100
per_hbeck17 = hbeck17/tot_crime17 *100
per_hwood17 = hwood17/tot_crime17 *100
per_mission17 = mission17/tot_crime17 *100
per_nhwood17 = nhwood17/tot_crime17 *100
per_newton17 = newton17/tot_crime17 * 100
per_northeast17 = northeast17/tot_crime17 *100
per_pacific17 = pacific17/tot_crime17 *100
per_rampart17 = rampart17/tot_crime17 *100
per_seast17 = seast17/tot_crime17 *100
per_swest17 = swest17/tot_crime17 *100
per_topanga17 = topanga17/tot_crime17*100
per_vnuys17 = vnuys17/tot_crime17 *100
per_wla17 = wla17/tot_crime17 *100
per_wvalley17 = wvalley17/tot_crime17 *100
per_wilshire17 = wilshire17/tot_crime17 *100


rate17 = pd.DataFrame({"":['77th St', 'Central', 'Devonshire', 'Foothill', 'Harbor',
                          'Hollenbeck', 'Hollywood', 'Mission', 'North Hollywood',
                          'Newton', 'Northeast',' Pacific', 'Rampart', 'Southeast',
                          'Southwest', 'Topanga', 'Van Nuys', 'West LA', 'West Valley',
                          'Wilshire'],
                           "Percentage of Crime": [per_seventyseven17crime, per_central17, per_dev17, per_fhill17, 
                                                         per_harb17,per_hbeck17, per_hwood17, per_mission17, per_nhwood17,
                                                         per_newton17,per_northeast17,per_pacific17, per_rampart17,
                                                         per_seast17, per_swest17, per_topanga17,
                                                         per_vnuys17,
                                                         per_wla17, per_wvalley17, per_wilshire17]})

rate17["Percentage of Crime"]= rate17["Percentage of Crime"].map("{:.2f}%".format)
rate17= rate17.set_index('')
rate17

                Percentage of Crime

77th St                       6.72%
Central                       5.16%
Devonshire                    4.61%
Foothill                      3.54%
Harbor                        4.19%
Hollenbeck                    3.93%
Hollywood                     4.89%
Mission                       4.69%
North Hollywood               5.38%
Newton                        5.09%
Northeast                     4.55%
 Pacific                      5.24%
Rampart                       4.17%
Southeast                     5.14%
Southwest                     6.18%
Topanga                       4.68%
Van Nuys                      4.67%
West LA                       3.91%
West Valley                   4.22%
Wilshire                      4.26%

In [25]:
#grab foreclosure data from 2018
crime18=crimedata_df[crimedata_df['Date Occurred Year']==2018]

#grab total foreclosure for 2018
tot_crime18=crime18["Area Name"].count()
crime18['Area Name'].unique()

#grab total crime for each area in 2018
seventyseven18crime=crime18["Area Name"].value_counts()["77th Street"]
central18=crime18["Area Name"].value_counts()["Central"]
#dev18=crime18["Area Name"].value_counts()["Devonshire"]
fhill18=crime18["Area Name"].value_counts()["Foothill"]
harb18=crime18["Area Name"].value_counts()["Harbor"]
hbeck18=crime18["Area Name"].value_counts()["Hollenbeck"]
hwood18=crime18["Area Name"].value_counts()["Hollywood"]
#mission18=crime18["Area Name"].value_counts()["Mission"]
nhwood18=crime18["Area Name"].value_counts()["N Hollywood"]
newton18=crime18["Area Name"].value_counts()["Newton"]
northeast18=crime18["Area Name"].value_counts()["Northeast"]
#pacific18=crime18["Area Name"].value_counts()["Pacific"]
rampart18=crime18["Area Name"].value_counts()["Rampart"]
#east18=crime18["Area Name"].value_counts()["Southeast"]
swest18=crime18["Area Name"].value_counts()["Southwest"]
#topanga18=crime18["Area Name"].value_counts()["Topanga"]
vnuys18=crime18["Area Name"].value_counts()["Van Nuys"]
wla18=crime18["Area Name"].value_counts()["West LA"]
#wvalley18=crime18["Area Name"].value_counts()["West Valley"]
wilshire18=crime18["Area Name"].value_counts()["Wilshire"]


# Percentage of crime per area
per_seventyseven18crime = seventyseven18crime/tot_crime18 *100
per_central18 = central18/tot_crime18 *100
#per_dev18 = dev18/tot_crime18 *100
per_fhill18 = fhill18/tot_crime18 *100
per_harb18 = harb18/tot_crime18 *100
per_hbeck18 = hbeck18/tot_crime18 *100
per_hwood18 = hwood18/tot_crime18 *100
#per_mission18 = mission18/tot_crime18 *100
per_nhwood18 = nhwood18/tot_crime18 *100
per_newton18 = newton18/tot_crime18 * 100
per_northeast18 = northeast18/tot_crime18 *100
#per_pacific18 = pacific18/tot_crime18 *100
per_rampart18 = rampart18/tot_crime18 *100
#per_seast18 = seast18/tot_crime18 *100
per_swest18 = swest18/tot_crime18 *100
#per_topanga18 = topanga18/tot_crime18*100
per_vnuys18 = vnuys18/tot_crime18 *100
per_wla18 = wla18/tot_crime18 *100
#per_wvalley18 = wvalley18/tot_crime18 *100
per_wilshire18 = wilshire18/tot_crime18 *100


rate18 = pd.DataFrame({"":['77th St', 'Central', 'Foothill', 'Harbor',
                          'Hollenbeck', 'Hollywood', 'North Hollywood',
                          'Newton', 'Northeast', 'Rampart',
                          'Southwest', 'Van Nuys', 'West LA',
                          'Wilshire'],
                           "Percentage of Crime": [per_seventyseven18crime, per_central18, per_fhill18, 
                                                         per_harb18,per_hbeck18, per_hwood18, per_nhwood18,
                                                         per_newton18,per_northeast18, per_rampart18, per_swest18,
                                                         per_vnuys18,
                                                         per_wla18, per_wilshire18]})

rate18["Percentage of Crime"]= rate18["Percentage of Crime"].map("{:.2f}%".format)
rate18= rate18.set_index('')
rate18

                Percentage of Crime

77th St                       0.00%
Central                      20.68%
Foothill                      0.00%
Harbor                       14.13%
Hollenbeck                   13.73%
Hollywood                    13.88%
North Hollywood               0.00%
Newton                        0.00%
Northeast                     0.00%
Rampart                      15.04%
Southwest                    22.45%
Van Nuys                      0.00%
West LA                       0.00%
Wilshire                      0.07%