In [1]:
import pandas as pd
import numpy as np
import json
import requests
import csv
from datetime import datetime

from config2018_11 import gkey

In [2]:
crimedata_df = pd.read_csv("../Source/crimedata_2018_11.csv")
#crimedata_df = pd.read_csv("C:\\Users\\Shubha\\Desktop\\Rutegers\\RUTGProject1\\Source\\crimedata16_19.csv")
crimedata_df.head()

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Weapon Description,Status Code,Status Description,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location
0,180311347,4/22/2018,4/9/2018,1,3,Southwest,374,310,BURGLARY,1607 0321,...,NaN,IC,Invest Cont,310,NaN,NaN,NaN,3800 2ND AV,NaN,"(34.0183, -118.3193)"
1,180311348,4/22/2018,4/22/2018,100,3,Southwest,338,626,INTIMATE PARTNER - SIMPLE ASSAULT,0401 0416 0446 1814 2000,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AA,Adult Arrest,626,NaN,NaN,NaN,39TH ST,HOOVER ST,"(34.0268, -118.2896)"
2,180311355,4/20/2018,4/20/2018,1910,3,Southwest,321,330,BURGLARY FROM VEHICLE,1300 0344 0329 1609,...,NaN,IC,Invest Cont,330,NaN,NaN,NaN,3500 S LA CIENEGA BL,NaN,"(34.0242, -118.3722)"
3,180311357,4/20/2018,4/20/2018,1845,3,Southwest,321,330,BURGLARY FROM VEHICLE,0329 1609 0352 1300 0344,...,NaN,IC,Invest Cont,330,NaN,NaN,NaN,3500 S LA CIENEGA BL,NaN,"(34.0242, -118.3722)"
4,180311364,4/23/2018,4/23/2018,200,3,Southwest,393,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510,NaN,NaN,NaN,4000 LEIMERT BL,NaN,"(34.0049, -118.3302)"

In [3]:
crimedata_df.count()

DR Number                 760
Date Reported             760
Date Occurred             760
Time Occurred             760
Area ID                   760
Area Name                 760
Reporting District        760
Crime Code                760
Crime Code Description    760
MO Codes                  708
Victim Age                760
Victim Sex                709
Victim Descent            709
Premise Code              760
Premise Description       760
Weapon Used Code          347
Weapon Description        347
Status Code               760
Status Description        760
Crime Code 1              760
Crime Code 2               33
Crime Code 3                1
Crime Code 4                0
Address                   760
Cross Street              125
Location                  760
dtype: int64

In [4]:
crimedata_df.dtypes
crimedata_df["Date Reported"]=pd.to_datetime(crimedata_df["Date Reported"])
# def unix_stamp(date):
#     return  datetime.datetime.strptime(date,"%d/%m/%Y")
crimedata_2018_11_df = crimedata_df[crimedata_df["Date Reported"] > datetime.strptime("2016-01-01", "%Y-%m-%d")]
crimedata_2018_11_df


# crimedata1619_df.shape
crimedata_2018_11_df.head()

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Weapon Description,Status Code,Status Description,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location
0,180311347,2018-04-22,4/9/2018,1,3,Southwest,374,310,BURGLARY,1607 0321,...,NaN,IC,Invest Cont,310,NaN,NaN,NaN,3800 2ND AV,NaN,"(34.0183, -118.3193)"
1,180311348,2018-04-22,4/22/2018,100,3,Southwest,338,626,INTIMATE PARTNER - SIMPLE ASSAULT,0401 0416 0446 1814 2000,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AA,Adult Arrest,626,NaN,NaN,NaN,39TH ST,HOOVER ST,"(34.0268, -118.2896)"
2,180311355,2018-04-20,4/20/2018,1910,3,Southwest,321,330,BURGLARY FROM VEHICLE,1300 0344 0329 1609,...,NaN,IC,Invest Cont,330,NaN,NaN,NaN,3500 S LA CIENEGA BL,NaN,"(34.0242, -118.3722)"
3,180311357,2018-04-20,4/20/2018,1845,3,Southwest,321,330,BURGLARY FROM VEHICLE,0329 1609 0352 1300 0344,...,NaN,IC,Invest Cont,330,NaN,NaN,NaN,3500 S LA CIENEGA BL,NaN,"(34.0242, -118.3722)"
4,180311364,2018-04-23,4/23/2018,200,3,Southwest,393,510,VEHICLE - STOLEN,NaN,...,NaN,IC,Invest Cont,510,NaN,NaN,NaN,4000 LEIMERT BL,NaN,"(34.0049, -118.3302)"

In [5]:
#Crating new csv for filttered data
crimedata_2018_11_df.to_csv("../Source/crimedata_2018_11_P.csv", index=False, header=True)

#Adding colunmn in new csv of crime data
crimedata_2018_11_df["Zip Codes"] = ""
crimedata_2018_11_df.head()

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Status Code,Status Description,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location,Zip Codes
0,180311347,2018-04-22,4/9/2018,1,3,Southwest,374,310,BURGLARY,1607 0321,...,IC,Invest Cont,310,NaN,NaN,NaN,3800 2ND AV,NaN,"(34.0183, -118.3193)",
1,180311348,2018-04-22,4/22/2018,100,3,Southwest,338,626,INTIMATE PARTNER - SIMPLE ASSAULT,0401 0416 0446 1814 2000,...,AA,Adult Arrest,626,NaN,NaN,NaN,39TH ST,HOOVER ST,"(34.0268, -118.2896)",
2,180311355,2018-04-20,4/20/2018,1910,3,Southwest,321,330,BURGLARY FROM VEHICLE,1300 0344 0329 1609,...,IC,Invest Cont,330,NaN,NaN,NaN,3500 S LA CIENEGA BL,NaN,"(34.0242, -118.3722)",
3,180311357,2018-04-20,4/20/2018,1845,3,Southwest,321,330,BURGLARY FROM VEHICLE,0329 1609 0352 1300 0344,...,IC,Invest Cont,330,NaN,NaN,NaN,3500 S LA CIENEGA BL,NaN,"(34.0242, -118.3722)",
4,180311364,2018-04-23,4/23/2018,200,3,Southwest,393,510,VEHICLE - STOLEN,NaN,...,IC,Invest Cont,510,NaN,NaN,NaN,4000 LEIMERT BL,NaN,"(34.0049, -118.3302)",

In [6]:
#find out the xip codes after giving values of lat and lng

url = "https://maps.googleapis.com/maps/api/geocode/json?"
params={'key':gkey}
#set the counter for output checking purpose
counter = 1
print("Begining")
for index,row in crimedata_2018_11_df.iterrows():
    location = row["Location "].replace('(', '').replace(')', '')
    params["latlng"] = location
    params["result_type"] = "postal_code"
    response = requests.get(url,params=params).json()
    result = response['results']
    if(len(result)>0):
        if('address_components' in result[0].keys()):
            if(len(result[0]['address_components'])>0):
                if('long_name' in result[0]['address_components'][0].keys()):
                    #print("Updating zipcode for: {}".format(location))
                    print(f"Record : {counter}")
                    crimedata_2018_11_df.loc[index,"Zip Codes"]=result[0]['address_components'][0]['long_name']
                    #counter increment
                    counter+=1

Begining
Record : 1
Record : 2
Record : 3
Record : 4
Record : 5
Record : 6
Record : 7
Record : 8
Record : 9
Record : 10
Record : 11
Record : 12
Record : 13
Record : 14
Record : 15
Record : 16
Record : 17
Record : 18
Record : 19
Record : 20
Record : 21
Record : 22
Record : 23
Record : 24
Record : 25
Record : 26
Record : 27
Record : 28
Record : 29
Record : 30
Record : 31
Record : 32
Record : 33
Record : 34
Record : 35
Record : 36
Record : 37
Record : 38
Record : 39
Record : 40
Record : 41
Record : 42
Record : 43
Record : 44
Record : 45
Record : 46
Record : 47
Record : 48
Record : 49
Record : 50
Record : 51
Record : 52
Record : 53
Record : 54
Record : 55
Record : 56
Record : 57
Record : 58
Record : 59
Record : 60
Record : 61
Record : 62
Record : 63
Record : 64
Record : 65
Record : 66
Record : 67
Record : 68
Record : 69
Record : 70
Record : 71
Record : 72
Record : 73
Record : 74
Record : 75
Record : 76
Record : 77
Record : 78
Record : 79
Record : 80
Record : 81
Record : 82
Record : 83
Record : 84
Record : 85
Record : 86
Record : 87
Record : 88
Record : 89
Record : 90
Record : 91
Record : 92
Record : 93
Record : 94
Record : 95
Record : 96
Record : 97
Record : 98
Record : 99
Record : 100
Record : 101
Record : 102
Record : 103
Record : 104
Record : 105
Record : 106
Record : 107
Record : 108
Record : 109
Record : 110
Record : 111
Record : 112
Record : 113
Record : 114
Record : 115
Record : 116
Record : 117
Record : 118
Record : 119
Record : 120
Record : 121
Record : 122
Record : 123
Record : 124
Record : 125
Record : 126
Record : 127
Record : 128
Record : 129
Record : 130
Record : 131
Record : 132
Record : 133
Record : 134
Record : 135
Record : 136
Record : 137
Record : 138
Record : 139
Record : 140
Record : 141
Record : 142
Record : 143
Record : 144
Record : 145
Record : 146
Record : 147
Record : 148
Record : 149
Record : 150
Record : 151
Record : 152
Record : 153
Record : 154
Record : 155
Record : 156
Record : 157
Record : 158
Record : 159
Record : 160
Record : 161
Record : 162
Record : 163
Record : 164
Record : 165
Record : 166
Record : 167
Record : 168
Record : 169
Record : 170
Record : 171
Record : 172
Record : 173
Record : 174
Record : 175
Record : 176
Record : 177
Record : 178
Record : 179
Record : 180
Record : 181
Record : 182
Record : 183
Record : 184
Record : 185
Record : 186
Record : 187
Record : 188
Record : 189
Record : 190
Record : 191
Record : 192
Record : 193
Record : 194
Record : 195
Record : 196
Record : 197
Record : 198
Record : 199
Record : 200
Record : 201
Record : 202
Record : 203
Record : 204
Record : 205
Record : 206
Record : 207
Record : 208
Record : 209
Record : 210
Record : 211
Record : 212
Record : 213
Record : 214
Record : 215
Record : 216
Record : 217
Record : 218
Record : 219
Record : 220
Record : 221
Record : 222
Record : 223
Record : 224
Record : 225
Record : 226
Record : 227
Record : 228
Record : 229
Record : 230
Record : 231
Record : 232
Record : 233
Record : 234
Record : 235
Record : 236
Record : 237
Record : 238
Record : 239
Record : 240
Record : 241
Record : 242
Record : 243
Record : 244
Record : 245
Record : 246
Record : 247
Record : 248
Record : 249
Record : 250
Record : 251
Record : 252
Record : 253
Record : 254
Record : 255
Record : 256
Record : 257
Record : 258
Record : 259
Record : 260
Record : 261
Record : 262
Record : 263
Record : 264
Record : 265
Record : 266
Record : 267
Record : 268
Record : 269
Record : 270
Record : 271
Record : 272
Record : 273
Record : 274
Record : 275
Record : 276
Record : 277
Record : 278
Record : 279
Record : 280
Record : 281
Record : 282
Record : 283
Record : 284
Record : 285
Record : 286
Record : 287
Record : 288
Record : 289
Record : 290
Record : 291
Record : 292
Record : 293
Record : 294
Record : 295
Record : 296
Record : 297
Record : 298
Record : 299
Record : 300
Record : 301
Record : 302
Record : 303
Record : 304
Record : 305
Record : 306
Record : 307
Record : 308
Record : 309
Record : 310
Record : 311
Record : 312
Record : 313
Record : 314
Record : 315
Record : 316
Record : 317
Record : 318
Record : 319
Record : 320
Record : 321
Record : 322
Record : 323
Record : 324
Record : 325
Record : 326
Record : 327
Record : 328
Record : 329
Record : 330
Record : 331
Record : 332
Record : 333
Record : 334
Record : 335
Record : 336
Record : 337
Record : 338
Record : 339
Record : 340
Record : 341
Record : 342
Record : 343
Record : 344
Record : 345
Record : 346
Record : 347
Record : 348
Record : 349
Record : 350
Record : 351
Record : 352
Record : 353
Record : 354
Record : 355
Record : 356
Record : 357
Record : 358
Record : 359
Record : 360
Record : 361
Record : 362
Record : 363
Record : 364
Record : 365
Record : 366
Record : 367
Record : 368
Record : 369
Record : 370
Record : 371
Record : 372
Record : 373
Record : 374
Record : 375
Record : 376
Record : 377
Record : 378
Record : 379
Record : 380
Record : 381
Record : 382
Record : 383
Record : 384
Record : 385
Record : 386
Record : 387
Record : 388
Record : 389
Record : 390
Record : 391
Record : 392
Record : 393
Record : 394
Record : 395
Record : 396
Record : 397
Record : 398
Record : 399
Record : 400
Record : 401
Record : 402
Record : 403
Record : 404
Record : 405
Record : 406
Record : 407
Record : 408
Record : 409
Record : 410
Record : 411
Record : 412
Record : 413
Record : 414
Record : 415
Record : 416
Record : 417
Record : 418
Record : 419
Record : 420
Record : 421
Record : 422
Record : 423
Record : 424
Record : 425
Record : 426
Record : 427
Record : 428
Record : 429
Record : 430
Record : 431
Record : 432
Record : 433
Record : 434
Record : 435
Record : 436
Record : 437
Record : 438
Record : 439
Record : 440
Record : 441
Record : 442
Record : 443
Record : 444
Record : 445
Record : 446
Record : 447
Record : 448
Record : 449
Record : 450
Record : 451
Record : 452
Record : 453
Record : 454
Record : 455
Record : 456
Record : 457
Record : 458
Record : 459
Record : 460
Record : 461
Record : 462
Record : 463
Record : 464
Record : 465
Record : 466
Record : 467
Record : 468
Record : 469
Record : 470
Record : 471
Record : 472
Record : 473
Record : 474
Record : 475
Record : 476
Record : 477
Record : 478
Record : 479
Record : 480
Record : 481
Record : 482
Record : 483
Record : 484
Record : 485
Record : 486
Record : 487
Record : 488
Record : 489
Record : 490
Record : 491
Record : 492
Record : 493
Record : 494
Record : 495
Record : 496
Record : 497
Record : 498
Record : 499
Record : 500
Record : 501
Record : 502
Record : 503
Record : 504
Record : 505
Record : 506
Record : 507
Record : 508
Record : 509
Record : 510
Record : 511
Record : 512
Record : 513
Record : 514
Record : 515
Record : 516
Record : 517
Record : 518
Record : 519
Record : 520
Record : 521
Record : 522
Record : 523
Record : 524
Record : 525
Record : 526
Record : 527
Record : 528
Record : 529
Record : 530
Record : 531
Record : 532
Record : 533
Record : 534
Record : 535
Record : 536
Record : 537
Record : 538
Record : 539
Record : 540
Record : 541
Record : 542
Record : 543
Record : 544
Record : 545
Record : 546
Record : 547
Record : 548
Record : 549
Record : 550
Record : 551
Record : 552
Record : 553
Record : 554
Record : 555
Record : 556
Record : 557
Record : 558
Record : 559
Record : 560
Record : 561
Record : 562
Record : 563
Record : 564
Record : 565
Record : 566
Record : 567
Record : 568
Record : 569
Record : 570
Record : 571
Record : 572
Record : 573
Record : 574
Record : 575
Record : 576
Record : 577
Record : 578
Record : 579
Record : 580
Record : 581
Record : 582
Record : 583
Record : 584
Record : 585
Record : 586
Record : 587
Record : 588
Record : 589
Record : 590
Record : 591
Record : 592
Record : 593
Record : 594
Record : 595
Record : 596
Record : 597
Record : 598
Record : 599
Record : 600
Record : 601
Record : 602
Record : 603
Record : 604
Record : 605
Record : 606
Record : 607
Record : 608
Record : 609
Record : 610
Record : 611
Record : 612
Record : 613
Record : 614
Record : 615
Record : 616
Record : 617
Record : 618
Record : 619
Record : 620
Record : 621
Record : 622
Record : 623
Record : 624
Record : 625
Record : 626
Record : 627
Record : 628
Record : 629
Record : 630
Record : 631
Record : 632
Record : 633
Record : 634
Record : 635
Record : 636
Record : 637
Record : 638

Record : 639
Record : 640
Record : 641
Record : 642
Record : 643
Record : 644
Record : 645
Record : 646
Record : 647
Record : 648
Record : 649
Record : 650
Record : 651
Record : 652
Record : 653
Record : 654
Record : 655
Record : 656
Record : 657
Record : 658
Record : 659
Record : 660
Record : 661
Record : 662
Record : 663
Record : 664
Record : 665
Record : 666
Record : 667
Record : 668
Record : 669
Record : 670
Record : 671
Record : 672
Record : 673
Record : 674
Record : 675
Record : 676
Record : 677
Record : 678
Record : 679
Record : 680
Record : 681
Record : 682
Record : 683
Record : 684
Record : 685
Record : 686
Record : 687
Record : 688
Record : 689
Record : 690
Record : 691
Record : 692
Record : 693
Record : 694
Record : 695
Record : 696
Record : 697
Record : 698
Record : 699
Record : 700
Record : 701
Record : 702
Record : 703
Record : 704
Record : 705
Record : 706
Record : 707
Record : 708
Record : 709
Record : 710
Record : 711
Record : 712
Record : 713
Record : 714
Record : 715
Record : 716
Record : 717
Record : 718
Record : 719
Record : 720
Record : 721
Record : 722
Record : 723
Record : 724
Record : 725
Record : 726
Record : 727
Record : 728
Record : 729
Record : 730
Record : 731
Record : 732
Record : 733
Record : 734
Record : 735
Record : 736
Record : 737
Record : 738
Record : 739
Record : 740
Record : 741
Record : 742
Record : 743
Record : 744
Record : 745
Record : 746
Record : 747
Record : 748
Record : 749
Record : 750
Record : 751
Record : 752
Record : 753
Record : 754
Record : 755
Record : 756
Record : 757
Record : 758
Record : 759
Record : 760

In [7]:
crimedata_2018_11_df

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Status Code,Status Description,Crime Code 1,Crime Code 2,Crime Code 3,Crime Code 4,Address,Cross Street,Location,Zip Codes
0,180311347,2018-04-22,4/9/2018,1,3,Southwest,374,310,BURGLARY,1607 0321,...,IC,Invest Cont,310,NaN,NaN,NaN,3800 2ND AV,NaN,"(34.0183, -118.3193)",90018
1,180311348,2018-04-22,4/22/2018,100,3,Southwest,338,626,INTIMATE PARTNER - SIMPLE ASSAULT,0401 0416 0446 1814 2000,...,AA,Adult Arrest,626,NaN,NaN,NaN,39TH ST,HOOVER ST,"(34.0268, -118.2896)",90007
2,180311355,2018-04-20,4/20/2018,1910,3,Southwest,321,330,BURGLARY FROM VEHICLE,1300 0344 0329 1609,...,IC,Invest Cont,330,NaN,NaN,NaN,3500 S LA CIENEGA BL,NaN,"(34.0242, -118.3722)",90016
3,180311357,2018-04-20,4/20/2018,1845,3,Southwest,321,330,BURGLARY FROM VEHICLE,0329 1609 0352 1300 0344,...,IC,Invest Cont,330,NaN,NaN,NaN,3500 S LA CIENEGA BL,NaN,"(34.0242, -118.3722)",90016
4,180311364,2018-04-23,4/23/2018,200,3,Southwest,393,510,VEHICLE - STOLEN,NaN,...,IC,Invest Cont,510,NaN,NaN,NaN,4000 LEIMERT BL,NaN,"(34.0049, -118.3302)",90008
5,180311365,2018-04-22,4/22/2018,2025,3,Southwest,311,624,BATTERY - SIMPLE ASSAULT,0329 0400 0554,...,IC,Invest Cont,624,NaN,NaN,NaN,5400 CARLIN ST,NaN,"(34.0305, -118.3615)",90016
6,180311366,2018-04-23,4/22/2018,2340,3,Southwest,332,626,INTIMATE PARTNER - SIMPLE ASSAULT,2000 1814 0416 2038,...,AO,Adult Other,626,900.0,NaN,NaN,30TH ST,BUCKINGHAM,"(34.0276, -118.3405)",90016
7,180311367,2018-04-21,4/21/2018,1620,3,Southwest,341,624,BATTERY - SIMPLE ASSAULT,0342 1251 1822 0400,...,IC,Invest Cont,624,NaN,NaN,NaN,3600 CARMONA AV,NaN,"(34.021, -118.3671)",90016
8,180311368,2018-04-21,4/20/2018,1730,3,Southwest,393,624,BATTERY - SIMPLE ASSAULT,1251 1259 0416 0446 0417 0429 1822 2024,...,IC,Invest Cont,624,NaN,NaN,NaN,9TH AV,43RD PL,"(34.0044, -118.3267)",90008
9,180311373,2018-04-20,4/19/2018,2130,3,Southwest,329,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",344,...,IC,Invest Cont,341,NaN,NaN,NaN,2800 S FIGUEROA ST,NaN,"(34.0262, -118.2772)",90007
10,180311374,2018-04-21,4/21/2018,1540,3,Southwest,332,624,BATTERY - SIMPLE ASSAULT,0416 0447 1822 1223 1309 0342,...,IC,Invest Cont,624,NaN,NaN,NaN,WEST ST,SANTA MONICA FY,"(34.0279, -118.343)",90016
11,180311375,2018-04-23,4/22/2018,2100,3,Southwest,377,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),2034 0329,...,IC,Invest Cont,745,NaN,NaN,NaN,1100 W 39TH ST,NaN,"(34.0155, -118.2999)",90037
12,180311376,2018-04-21,4/18/2018,2230,3,Southwest,314,956,"LETTERS, LEWD - TELEPHONE CALLS, LEWD",1202 0913 1906,...,IC,Invest Cont,956,NaN,NaN,NaN,2300 3RD AV,NaN,"(34.0358, -118.32)",90018
13,180311377,2018-04-23,4/23/2018,750,3,Southwest,325,480,BIKE - STOLEN,0344 2004 1251,...,IC,Invest Cont,480,NaN,NaN,NaN,2700 MENLO AV,NaN,"(34.0304, -118.2903)",90007
14,180311384,2018-04-23,4/22/2018,1640,3,Southwest,356,440,THEFT PLAIN - PETTY ($950 & UNDER),0344 1202 2032,...,IC,Invest Cont,440,NaN,NaN,NaN,1700 W JEFFERSON BL,NaN,"(34.0256, -118.3061)",90018
15,180311385,2018-04-23,3/19/2018,900,3,Southwest,393,440,THEFT PLAIN - PETTY ($950 & UNDER),0344 2032,...,IC,Invest Cont,440,NaN,NaN,NaN,4100 11TH AV,NaN,"(34.01, -118.3296)",90008
16,180311386,2018-04-22,4/12/2018,1200,3,Southwest,325,354,THEFT OF IDENTITY,0100 0930,...,IC,Invest Cont,354,NaN,NaN,NaN,1400 W 27TH ST,NaN,"(34.0305, -118.2915)",90007
17,180311387,2018-04-22,4/22/2018,2020,3,Southwest,375,624,BATTERY - SIMPLE ASSAULT,0360 0444 0602,...,IC,Invest Cont,624,NaN,NaN,NaN,1600 EXPOSITION BL,NaN,"(34.0183, -118.3089)",90018
18,180311388,2018-04-23,4/22/2018,2100,3,Southwest,353,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),1202 0329 1607,...,IC,Invest Cont,745,NaN,NaN,NaN,3700 COLISEUM ST,NaN,"(34.0209, -118.3406)",90016
19,180311389,2018-04-23,4/20/2018,1300,3,Southwest,338,480,BIKE - STOLEN,0344 1251,...,IC,Invest Cont,480,NaN,NaN,NaN,1300 W 29TH ST,NaN,"(34.0284, -118.2888)",90007
20,180311390,2018-04-21,4/21/2018,1640,3,Southwest,321,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),1300 0329,...,IC,Invest Cont,745,NaN,NaN,NaN,3500 S LA CIENEGA BL,NaN,"(34.0242, -118.3722)",90016
21,180311395,2018-04-23,4/23/2018,200,3,Southwest,395,626,INTIMATE PARTNER - SIMPLE ASSAULT,1814 2000 0431 1310 0448 0429 0416 0319 0369 0408,...,IC,Invest Cont,626,NaN,NaN,NaN,1500 W MARTIN LUTHER KING BL,NaN,"(34.0109, -118.3084)",90062
22,180311403,2018-04-18,4/1/2018,302,3,Southwest,311,956,"LETTERS, LEWD - TELEPHONE CALLS, LEWD",1906,...,IC,Invest Cont,956,NaN,NaN,NaN,2700 CLYDE AV,NaN,"(34.0305, -118.3677)",90016
23,180311404,2018-04-23,4/23/2018,1245,3,Southwest,357,236,INTIMATE PARTNER - AGGRAVATED ASSAULT,1402 0334 1813 1243 2033 0445 1223 2000,...,AO,Adult Other,236,998.0,NaN,NaN,1200 W 37TH DR,NaN,"(34.0191, -118.2944)",90007
24,180311405,2018-04-23,4/22/2018,2330,3,Southwest,392,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",329,...,IC,Invest Cont,740,NaN,NaN,NaN,2ND AV,VERNON,"(34.0037, -118.3192)",90008
25,180311406,2018-04-22,4/22/2018,1400,3,Southwest,355,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,0421 0446 0913 1810,...,IC,Invest Cont,930,NaN,NaN,NaN,1800 W JEFFERSON BL,NaN,"(34.0256, -118.3089)",90018
26,180311407,2018-04-22,4/22/2018,550,3,Southwest,329,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,0443 0104 2004 1822,...,IC,Invest Cont,930,NaN,NaN,NaN,2600 S FIGUEROA ST,NaN,"(34.0282, -118.276)",90007
27,180311411,2018-04-22,4/22/2018,1400,3,Southwest,355,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,0421 0446 0913 1810,...,IC,Invest Cont,930,NaN,NaN,NaN,1800 W JEFFERSON BL,NaN,"(34.0256, -118.3089)",90018
28,180311415,2018-04-23,4/22/2018,1200,3,Southwest,393,310,BURGLARY,1300 0352 1607 0386 0397,...,IC,Invest Cont,310,NaN,NaN,NaN,4200 LEIMERT BL,NaN,"(34.0082, -118.3263)",90008
29,180311416,2018-04-23,4/2/2018,1000,3,Southwest,393,310,BURGLARY,1202 0344 0397 1607,...,IC,Invest Cont,310,NaN,NaN,NaN,4200 LEIMERT BL,NaN,"(34.0082, -118.3263)",90008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
730,180312680,2018-05-11,5/11/2018,1920,3,Southwest,356,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),0344 1606 1822,...,IC,Invest Cont,420,NaN,NaN,NaN,1500 W 36TH PL,NaN,"(34.0219, -118.3031)",90018
731,180312684,2018-05-12,5/12/2018,1245,3,Southwest,378,510,VEHICLE - STOLEN,NaN,...,IC,Invest Cont,510,NaN,NaN,NaN,700 EXPOSITION PARK DR,NaN,"(34.0154, -118.2884)",90037
732,180312685,2018-05-11,5/4/2018,1130,3,Southwest,334,354,THEFT OF IDENTITY,0100 1822,...,IC,Invest Cont,354,NaN,NaN,NaN,3000 12TH AV,NaN,"(34.0276, -118.3317)",90018
733,180312686,2018-05-11,4/28/2018,1430,3,Southwest,398,354,THEFT OF IDENTITY,0100 1822 0922,...,IC,Invest Cont,354,NaN,NaN,NaN,700 W 43RD PL,NaN,"(34.0046, -118.2857)",90037
734,180312693,2018-05-11,5/11/2018,1345,3,Southwest,376,624,BATTERY - SIMPLE ASSAULT,1822 1309 1026 0416 0446 0429,...,IC,Invest Cont,624,NaN,NaN,NaN,1400 W MARTIN LUTHER KING JR BL,NaN,"(34.0145, -118.3045)",90062
735,180312694,2018-05-11,5/11/2018,1350,3,Southwest,355,624,BATTERY - SIMPLE ASSAULT,0329 0558 2002 0321 0400 0602,...,IC,Invest Cont,624,NaN,NaN,NaN,3500 CIMARRON ST,NaN,"(34.0246, -118.3156)",90018
736,180312695,2018-05-11,5/11/2018,2100,3,Southwest,328,624,BATTERY - SIMPLE ASSAULT,0416 0446 1278 2021 1310 0601,...,AA,Adult Arrest,624,NaN,NaN,NaN,FIGUEROA,37TH,"(34.0268, -118.2808)",90007
737,180312698,2018-05-11,5/11/2018,1045,3,Southwest,398,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",1300 0329,...,IC,Invest Cont,740,NaN,NaN,NaN,700 W 43RD ST,NaN,"(34.0054, -118.2857)",90037
738,180312699,2018-05-11,5/11/2018,720,3,Southwest,325,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",1822 0329,...,IC,Invest Cont,740,NaN,NaN,NaN,1400 W ADAMS BL,NaN,"(34.0328, -118.2915)",90007
739,180312700,2018-05-11,5/6/2018,2030,3,Southwest,362,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",1300 0329,...,IC,Invest Cont,740,NaN,NaN,NaN,MUIRFIELD,COLISEUM,"(34.0183, -118.3423)",90016
740,180312701,2018-05-12,3/31/2018,800,3,Southwest,317,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",1300 0329,...,IC,Invest Cont,740,NaN,NaN,NaN,1400 W ADAMS BL,NaN,"(34.0349, -118.2959)",90007
741,180312706,2018-05-12,5/12/2018,1242,3,Southwest,328,933,PROWLER,1402 1251 1822 2004,...,IC,Invest Cont,933,998.0,NaN,NaN,600 W 28TH ST,NaN,"(34.0261, -118.2773)",90007
742,180312707,2018-05-12,5/11/2018,2000,3,Southwest,395,331,THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER),0344 1608 0385,...,IC,Invest Cont,331,NaN,NaN,NaN,1900 W 43RD ST,NaN,"(34.0055, -118.3138)",90062
743,180312708,2018-05-12,5/12/2018,1600,3,Southwest,363,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",0416 0447 1202 2004 1218 0913,...,IC,Invest Cont,230,NaN,NaN,NaN,MARLTON AV,MARTIN LUTHER KING JR BL,"(34.0105, -118.3398)",90008
744,180312710,2018-05-12,5/11/2018,1400,3,Southwest,379,440,THEFT PLAIN - PETTY ($950 & UNDER),0344 2032 1266,...,IC,Invest Cont,440,NaN,NaN,NaN,1100 EXPOSITION BL,NaN,"(34.0182, -118.2944)",90007
745,180312711,2018-05-12,5/12/2018,1300,3,Southwest,361,350,"THEFT, PERSON",1309 0344 1822 0346 0448 1202,...,IC,Invest Cont,350,NaN,NaN,NaN,LA BREA AV,RODEO RD,"(34.0216, -118.3556)",90016
746,180312713,2018-05-12,3/12/2018,1200,3,Southwest,395,354,THEFT OF IDENTITY,337,...,IC,Invest Cont,354,NaN,NaN,NaN,1800 W VERNON AV,NaN,"(34.0073, -118.3108)",90062
747,180312714,2018-05-12,5/11/2018,2100,3,Southwest,373,666,"BUNCO, ATTEMPT",1822 0800 0701 1309 1402,...,IC,Invest Cont,666,NaN,NaN,NaN,3700 CRENSHAW BL,NaN,"(34.0182, -118.3349)",90008
748,180312716,2018-05-12,5/12/2018,2020,3,Southwest,398,210,ROBBERY,0344 0342 0305 0346 0446 0416 1822,...,IC,Invest Cont,210,NaN,NaN,NaN,HOOVER ST,43RD ST,"(34.0054, -118.2872)",90037
749,180312717,2018-05-12,5/12/2018,1655,3,Southwest,396,624,BATTERY - SIMPLE ASSAULT,1202 0448 0416 0553,...,IC,Invest Cont,624,NaN,NaN,NaN,800 W MARTIN LUTHER KING JR BL,NaN,"(34.0111, -118.2872)",90037
750,180312718,2018-05-12,5/12/2018,1720,3,Southwest,361,624,BATTERY - SIMPLE ASSAULT,0446 0416 0913 1815 1824 2024 1258 1251,...,IC,Invest Cont,624,NaN,NaN,NaN,URSULA,PINAFORE,"(34.0127, -118.3525)",90008
751,180312719,2018-05-06,5/6/2018,800,3,Southwest,362,440,THEFT PLAIN - PETTY ($950 & UNDER),0344 1606 1202,...,IC,Invest Cont,440,NaN,NaN,NaN,3900 COCO AV,NaN,"(34.0155, -118.3497)",90008
752,180312729,2018-05-13,5/13/2018,137,3,Southwest,331,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",1402 0906 1816 0430 1407 0216 1100 0302 1300 0334,...,AA,Adult Arrest,230,NaN,NaN,NaN,4900 W ADAMS BL,NaN,"(34.0326, -118.347)",90016
753,180312730,2018-05-12,5/12/2018,2030,3,Southwest,363,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),0325 0104 0378,...,IC,Invest Cont,442,NaN,NaN,NaN,4000 CRENSHAW BL,NaN,"(34.0124, -118.3351)",90008
754,180312732,2018-05-13,5/13/2018,137,3,Southwest,331,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",0906 1407 1402 1822 0216 0302 0334 1310 0430 1240,...,AA,Adult Arrest,230,NaN,NaN,NaN,4900 W ADAMS BL,NaN,"(34.0326, -118.347)",90016
755,180312733,2018-05-13,5/13/2018,137,3,Southwest,331,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",0906 1407 1402 1822 0216 0302 0334 1310 0430 1240,...,AA,Adult Arrest,230,NaN,NaN,NaN,4900 W ADAMS BL,NaN,"(34.0326, -118.347)",90016
756,180312734,2018-05-12,5/12/2018,1058,3,Southwest,325,480,BIKE - STOLEN,344,...,IC,Invest Cont,480,NaN,NaN,NaN,2800 ELLENDALE PL,NaN,"(34.0307, -118.2923)",90007
757,180312736,2018-05-11,5/11/2018,2130,3,Southwest,363,624,BATTERY - SIMPLE ASSAULT,0444 0913 2021,...,IC,Invest Cont,624,NaN,NaN,NaN,4100 PALMWOOD DR,NaN,"(34.0137, -118.3435)",90008
758,180312737,2018-05-12,5/12/2018,310,3,Southwest,363,624,BATTERY - SIMPLE ASSAULT,0360 0448 0416 0446,...,AO,Adult Other,624,NaN,NaN,NaN,4100 BUCKINGHAM RD,NaN,"(34.0121, -118.3423)",90008
759,180312738,2018-05-11,5/11/2018,2115,3,Southwest,398,946,OTHER MISCELLANEOUS CRIME,0554 0602 0603 2021,...,AO,Adult Other,946,NaN,NaN,NaN,500 W 42ND ST,NaN,"(34.0071, -118.2827)",90037

In [9]:
crimedata_2018_11_df.to_csv("../Source/crimedata_2018_11_P.csv", index=False, header=True)

In [10]:
crimedata2018_11 = pd.read_csv("../Source/crimedata_2018_11_P.csv")
crimedata2018_11.count()

DR Number                 760
Date Reported             760
Date Occurred             760
Time Occurred             760
Area ID                   760
Area Name                 760
Reporting District        760
Crime Code                760
Crime Code Description    760
MO Codes                  708
Victim Age                760
Victim Sex                709
Victim Descent            709
Premise Code              760
Premise Description       760
Weapon Used Code          347
Weapon Description        347
Status Code               760
Status Description        760
Crime Code 1              760
Crime Code 2               33
Crime Code 3                1
Crime Code 4                0
Address                   760
Cross Street              125
Location                  760
Zip Codes                 760
dtype: int64