In [21]:
import pandas as pd
import numpy as np
import os
import csv

In [38]:
csv_path = "../Source/ForeclosureData/Registered_Foreclosure_Properties_2016-2018_Combined.csv"
forcls_df = pd.read_csv(csv_path)

forcls_df = forcls_df[np.isfinite(forcls_df['PropertyZip'])]

forcls_df['PropertyZip'] = forcls_df['PropertyZip'].astype(int)
forcls_df['RegisteredDate'] = forcls_df['RegisteredDate'].astype('datetime64')

forcls_df['RegisteredDate']=forcls_df['RegisteredDate'].apply(lambda yr:yr.year)

forcls_df.drop(columns=['APN','Lender'],inplace=True)
forcls_df.dropna()

forcls_df

,RegisteredDate,PropertyType,PropertyAddress,PropertyCity,PropertyState,PropertyZip,CouncilDistrict
0,2016,Single Family,"17725 W ORNA DR\r\nLOS ANGELES, CA 91344\r\n(3...",LOS ANGELES,CA,91344,12
1,2016,Single Family,"2695 N LA CUESTA DR\r\nLOS ANGELES, CA 90046\r...",LOS ANGELES,CA,90046,4
2,2016,Single Family,"841 W 148TH ST\r\nLOS ANGELES, CA 90247\r\n(33...",LOS ANGELES,CA,90247,15
3,2016,Single Family,"11826 W SNELLING ST\r\nLOS ANGELES, CA 91352\r...",LOS ANGELES,CA,91352,6
4,2016,Single Family,"17431 W EMILITA ST\r\nLOS ANGELES, CA 91316",LOS ANGELES,CA,91316,5
5,2016,Single Family,"2912 E PENNSYLVANIA AVE\r\nLOS ANGELES, CA 900...",LOS ANGELES,CA,90033,14
6,2016,Single Family,"2906 S HAUSER BLVD\r\nLOS ANGELES, CA 90016\r\...",LOS ANGELES,CA,90016,10
7,2016,Single Family,"20134 W LEADWELL\r\nLOS ANGELES, CA 91306",LOS ANGELES,CA,91306,3
8,2016,Single Family,"5228 S MANHATTAN PL\r\nLOS ANGELES, CA 90062\r...",LOS ANGELES,CA,90062,8
9,2016,Single Family,"12760 W BLYTHE ST\r\nLOS ANGELES, CA 91605\r\n...",LOS ANGELES,CA,91605,2
10,2016,Single Family,"10030 OWENSMOUTH\r\nLOS ANGELES, CA 91311\r\n(...",LOS ANGELES,CA,91311,12
11,2016,Single Family,"18756 W LEADWELL ST\r\nLOS ANGELES, CA 91335\r...",LOS ANGELES,CA,91335,3
12,2016,Single Family,"9604 N HILLHAVEN AVE\r\nLOS ANGELES, CA 91042\...",LOS ANGELES,CA,91042,7
13,2016,Multi-Family,"3727 S VAN NESS AVE\r\nLOS ANGELES, CA 90018\r...",LOS ANGELES,CA,90018,8
14,2016,Multi-Family,"1927 1/2 E 111TH ST\r\nLOS ANGELES, CA 90059\r...",LOS ANGELES,CA,90059,15
15,2016,Single Family,"949 N RUTLAND AVE\r\nLOS ANGELES, CA 90042\r\n...",LOS ANGELES,CA,90042,14
16,2016,Single Family,"14627 W GLEDHILL ST\r\nLOS ANGELES, CA 91402\r...",LOS ANGELES,CA,91402,6
17,2016,Single Family,"10408 N LAS LUNITAS AVE\r\nLOS ANGELES, CA 910...",LOS ANGELES,CA,91042,7
18,2016,Single Family,"15437 W KINZIE ST\r\nLOS ANGELES, CA 91343\r\n...",LOS ANGELES,CA,91343,7
19,2016,Single Family,"2923 W 74TH ST\r\nLOS ANGELES, CA 90043\r\n(33...",LOS ANGELES,CA,90043,8
20,2016,Single Family,"15345 W HART ST\r\nVAN NUYS, CA 91406\r\n(34.1...",VAN NUYS,CA,91406,6
21,2016,Single Family,"11115 S DENVER AVE\r\nLOS ANGELES, CA 90044\r\...",LOS ANGELES,CA,90044,8
22,2016,Single Family,"18701 W LASSEN ST\r\nLOS ANGELES, CA 91324\r\n...",LOS ANGELES,CA,91324,12
23,2016,Single Family,"1541 W 218TH ST\r\nLOS ANGELES, CA 90501\r\n(3...",LOS ANGELES,CA,90501,15
24,2016,Single Family,"10465 N WILLOWBRAE AVE\r\nLOS ANGELES, CA 9131...",LOS ANGELES,CA,91311,12
25,2016,Single Family,"7913 N LOUISE AVE\r\nLOS ANGELES, CA 91325\r\n...",LOS ANGELES,CA,91325,12
26,2016,Single Family,"6939 N SUNNY BRAE AVE\r\nLOS ANGELES, CA 91306...",LOS ANGELES,CA,91306,3
27,2016,Single Family,"23323 W BALMORAL LANE\r\nLOS ANGELES, CA 91307...",LOS ANGELES,CA,91307,12
28,2016,Single Family,"19730 W SEPTO ST\r\nLOS ANGELES, CA 91311\r\n(...",LOS ANGELES,CA,91311,12
29,2016,Single Family,"9309 N ARLETA AVE\r\nLOS ANGELES, CA 91331\r\n...",LOS ANGELES,CA,91331,6
...,...,...,...,...,...,...,...
16144,2018,Single Family,5845 S CIMARRON ST,LOS ANGELES,CA,90047,8
16145,2018,Single Family,8923 N KESTER AVE,LOS ANGELES,CA,91402,6
16146,2018,Single Family,6603 S ST ANDREWS PL,LOS ANGELES,CA,90047,8
16147,2018,Single Family,4868 N ADELE CT,LOS ANGELES,CA,91364,3
16148,2018,Single Family,6007 N SIMPSON AVE,LOS ANGELES,CA,91606,2
16149,2018,Single Family,9447 N BRANDON CT,LOS ANGELES,CA,91325,12
16150,2018,Single Family,542 W 105TH ST,LOS ANGELES,CA,90044,8
16151,2018,Single Family,762 W EL SEGUNDO BLVD,LOS ANGELES,CA,90247,15
16152,2018,Single Family,4938 E O'SULLIVAN DR,LOS ANGELES,CA,90032,14
16153,2018,Single Family,8846 N MOONBEAM AVE,LOS ANGELES,CA,91402,6
16154,2018,Single Family,5412 N FALLBROOK AVE,LOS ANGELES,CA,91367,3
16155,2018,Single Family,4919 S 7TH AVE,LOS ANGELES,CA,90043,8
16156,2018,Single Family,7363 N BOTHWELL RD,LOS ANGELES,CA,91335,3
16157,2018,Single Family,4725 W DON PORFIRIO PL,LOS ANGELES,CA,90008,8
16158,2018,Single Family,5329 S 2ND AVE,LOS ANGELES,CA,90043,8
16159,2018,Single Family,9419 N MONOGRAM AVE,LOS ANGELES,CA,91343,12
16160,2018,Single Family,6400 N KENWATER PL,LOS ANGELES,CA,91307,12
16161,2018,Single Family,7719 S HINDRY AVE,LOS ANGELES,CA,90045,11
16162,2018,Single Family,6624 S 2ND AVE,LOS ANGELES,CA,90043,8
16163,2018,Single Family,9340 N CREBS AVE,LOS ANGELES,CA,91324,12
16164,2018,Single Family,876 W CRESTWOOD ST,SAN PEDRO,CA,90731,15
16165,2018,Single Family,5505 N AURA AVE,LOS ANGELES,CA,91356,3
16166,2018,Single Family,5612 N BELLINGHAM AVE,LOS ANGELES,CA,91607,2
16167,2018,Multi-Family,7108 1/2 S RAMSGATE AVE,WESTCHESTER,CA,90045,11
16168,2018,Single Family,7049 N DE CELIS PL,LOS ANGELES,CA,91406,6
16169,2018,Multi-Family,9517 1/2 S CLOVIS AVE,LOS ANGELES,CA,90002,8
16170,2018,Multi-Family,9501 S BANDERA ST,LOS ANGELES,CA,90002,15
16171,2018,Single Family,835 N ONEONTA DR,LOS ANGELES,CA,90065,1
16172,2018,Single Family,5910 S EDGEMAR AVE,LOS ANGELES,CA,90043,8
16173,2018,Single Family,7000 N OAKDALE AVE,LOS ANGELES,CA,91306,3

In [37]:
forcls_df.groupby(['RegisteredDate','CouncilDistrict','PropertyZip',]).count()

                                            PropertyType  PropertyAddress  \
RegisteredDate CouncilDistrict PropertyZip
2016           0               90302                   1                1
                               91302                   1                1
               1               90006                  25               25
                               90007                   3                3
                               90012                   5                5
                               90015                   2                2
                               90017                   9                9
                               90026                   6                6
                               90031                  45               45
                               90041                   2                2
                               90042                  33               33
                               90057                   4                4
                               90064                   2                2
                               90065                  64               64
                               90402                   1                1
               2               90068                   1                1
                               91352                  37               37
                               91401                  35               35
                               91405                  32               32
                               91406                   3                3
                               91423                   1                1
                               91504                   7                7
                               91505                   1                1
                               91601                  34               34
                               91602                   8                8
                               91604                  70               70
                               91605                  68               68
                               91606                  84               84
                               91607                  56               56
               3               91303                  39               39
...                                                  ...              ...
2018           13              90027                   4                4
                               90028                   1                1
                               90029                   8                8
                               90031                   3                3
                               90038                   4                4
                               90039                  13               13
                               90065                   3                3
               14              90012                   5                5
                               90015                   1                1
                               90017                   2                2
                               90021                   1                1
                               90023                   5                5
                               90032                  39               39
                               90033                  15               15
                               90041                  26               26
                               90042                  29               29
                               90063                   9                9
                               90065                   4                4
               15              90002                  24               24
                               90044                   9                9
                               90059                  25               25
                               90061                  12               12
                               90247                  10               10
                               90248                   6                6
                               90501                  10               10
                               90710                  11               11
                               90717                   2                2
                               90731                  41               41
                               90732                  21               21
                               90744                  36               36

                                            PropertyCity  PropertyState
RegisteredDate CouncilDistrict PropertyZip
2016           0               90302                   1              1
                               91302                   1              1
               1               90006                  25             25
                               90007                   3              3
                               90012                   5              5
                               90015                   2              2
                               90017                   9              9
                               90026                   6              6
                               90031                  45             45
                               90041                   2              2
                               90042                  33             33
                               90057                   4              4
                               90064                   2              2
                               90065                  64             64
                               90402                   1              1
               2               90068                   1              1
                               91352                  37             37
                               91401                  35             35
                               91405                  32             32
                               91406                   3              3
                               91423                   1              1
                               91504                   7              7
                               91505                   1              1
                               91601                  34             34
                               91602                   8              8
                               91604                  70             70
                               91605                  68             68
                               91606                  84             84
                               91607                  56             56
               3               91303                  39             39
...                                                  ...            ...
2018           13              90027                   4              4
                               90028                   1              1
                               90029                   8              8
                               90031                   3              3
                               90038                   4              4
                               90039                  13             13
                               90065                   3              3
               14              90012                   5              5
                               90015                   1              1
                               90017                   2              2
                               90021                   1              1
                               90023                   5              5
                               90032                  39             39
                               90033                  15             15
                               90041                  26             26
                               90042                  29             29
                               90063                   9              9
                               90065                   4              4
               15              90002                  24             24
                               90044                   9              9
                               90059                  25             25
                               90061                  12             12
                               90247                  10             10
                               90248                   6              6
                               90501                  10             10
                               90710                  11             11
                               90717                   2              2
                               90731                  41             41
                               90732                  21             21
                               90744                  36             36

[588 rows x 4 columns]